### ISSUE TITLE
BGP command 'no bgp default ipv4-unicast' is not implemented (for IPv6)

### ISSUE THREAD

**Issue by xivamar** [MERAprojects/ops-cli#6]
The command `no bgp default ipv4-unicast` isn't implemented:

```
      switch(config)# router bgp 64500 
      switch(config-router)# no bgp default ipv4-unicast
      This command is not yet implemented but here are the parameters:
      argc = 0
      switch(config-router)#
```

In Cisco without configuring `no bgp default ipv4-unicast` only IPv4 will be advertised.

**Comment by rleykin** [comment]
As agreed with Marina, this issue does not look as actual issue for the current OpenSwitch version, since there are no default settings for IPv4 advertisements only as in CISCO. So at the moment this can be closed.
